import type { ChatLanguage } from "../../types/help";

const en = {
  title: "Settings",
  intro: "Make your visit comfortable.",
  language: "Language",
  guideLanguage: "Guide language",
  languageHint:
    "This changes the language across visitor pages. Staff language is configured separately in Staff Settings.",
  accessibility: "Accessibility",
  textSize: "Text size",
  normal: "Normal",
  large: "Large",
  extraLarge: "Extra large",
  darkMode: "Dark mode",
  highContrast: "High contrast",
  reduceMotion: "Reduce motion",
  notifications: "Notifications",
  inApp: "In-app notifications",
  helpConfirmations: "Help request confirmations",
  feedbackConfirmations: "Feedback confirmations",
  test: "Show test notification",
  testMessage: "This is a test help notification.",
  notificationHint:
    "Save your in-app notification preferences here. Notification delivery can be connected by the team later. Use the test button to preview a banner.",
  account: "Account settings",
  accountHint: "Account features will be added by the account team.",
  reset: "Reset settings",
  resetQuestion: "Restore default settings?",
  cancel: "Cancel",
  restore: "Restore defaults",
  saved: "Saved automatically in this browser.",
  storageError:
    "Browser storage is unavailable. Changes work for this session only.",
  home: "Home",
  trail: "Discovery Trail",
  chatbot: "Chatbot",
  help: "Help",
  resetSaved: "Settings restored.",
  accountPlaceholder: "Account settings — coming soon",
};
const zh = {
  title: "设置",
  intro: "让您的参观更舒适。",
  language: "语言",
  guideLanguage: "导览语言",
  languageHint: "此设置会更改所有访客页面的语言。员工语言可在员工设置中单独配置。",
  accessibility: "无障碍",
  textSize: "文字大小",
  normal: "标准",
  large: "大",
  extraLarge: "特大",
  darkMode: "深色模式",
  highContrast: "高对比度",
  reduceMotion: "减少动画",
  notifications: "通知",
  inApp: "应用内通知",
  helpConfirmations: "求助请求确认",
  feedbackConfirmations: "反馈确认",
  test: "显示测试通知",
  testMessage: "这是一条测试求助通知。",
  notificationHint:
    "在此保存应用内通知偏好。团队之后可以连接通知发送功能。使用测试按钮预览横幅。",
  account: "账户设置",
  accountHint: "账户功能将由账户团队添加。",
  reset: "重置设置",
  resetQuestion: "恢复默认设置？",
  cancel: "取消",
  restore: "恢复默认设置",
  saved: "自动保存在此浏览器中。",
  storageError: "浏览器存储不可用。更改仅适用于本次会话。",
  home: "首页",
  trail: "探索之旅",
  chatbot: "聊天机器人",
  help: "帮助",
  resetSaved: "设置已恢复。",
  accountPlaceholder: "账户设置 — 即将推出",
};
const ms = {
  title: "Tetapan",
  intro: "Jadikan lawatan anda selesa.",
  language: "Bahasa",
  guideLanguage: "Bahasa panduan",
  languageHint:
    "Ini menukar bahasa semua halaman pelawat. Bahasa kakitangan ditetapkan secara berasingan dalam Tetapan Kakitangan.",
  accessibility: "Kebolehcapaian",
  textSize: "Saiz teks",
  normal: "Biasa",
  large: "Besar",
  extraLarge: "Sangat besar",
  darkMode: "Mod gelap",
  highContrast: "Kontras tinggi",
  reduceMotion: "Kurangkan animasi",
  notifications: "Pemberitahuan",
  inApp: "Pemberitahuan dalam aplikasi",
  helpConfirmations: "Pengesahan permintaan bantuan",
  feedbackConfirmations: "Pengesahan maklum balas",
  test: "Papar pemberitahuan ujian",
  testMessage: "Ini ialah pemberitahuan bantuan ujian.",
  notificationHint:
    "Simpan pilihan pemberitahuan dalam aplikasi di sini. Pasukan boleh menyambungkan penghantaran pemberitahuan kemudian. Gunakan butang ujian untuk melihat sepanduk.",
  account: "Tetapan akaun",
  accountHint: "Ciri akaun akan ditambah oleh pasukan akaun.",
  reset: "Tetapkan semula",
  resetQuestion: "Pulihkan tetapan lalai?",
  cancel: "Batal",
  restore: "Pulihkan lalai",
  saved: "Disimpan secara automatik dalam pelayar ini.",
  storageError:
    "Storan pelayar tidak tersedia. Perubahan hanya digunakan untuk sesi ini.",
  home: "Utama",
  trail: "Jejak Penemuan",
  chatbot: "Chatbot",
  help: "Bantuan",
  resetSaved: "Tetapan dipulihkan.",
  accountPlaceholder: "Tetapan akaun — akan datang",
};
const ta = {
  title: "அமைப்புகள்",
  intro: "உங்கள் வருகையை வசதியாக்குங்கள்.",
  language: "மொழி",
  guideLanguage: "வழிகாட்டி மொழி",
  languageHint:
    "இது அனைத்து பார்வையாளர் பக்கங்களின் மொழியையும் மாற்றும். பணியாளர் மொழியை பணியாளர் அமைப்புகளில் தனியாக அமைக்கலாம்.",
  accessibility: "அணுகல்தன்மை",
  textSize: "எழுத்து அளவு",
  normal: "சாதாரணம்",
  large: "பெரியது",
  extraLarge: "மிகப் பெரியது",
  darkMode: "இருண்ட பயன்முறை",
  highContrast: "அதிக நிற வேறுபாடு",
  reduceMotion: "அசைவைக் குறைக்கவும்",
  notifications: "அறிவிப்புகள்",
  inApp: "செயலியில் அறிவிப்புகள்",
  helpConfirmations: "உதவி கோரிக்கை உறுதிப்படுத்தல்கள்",
  feedbackConfirmations: "கருத்து உறுதிப்படுத்தல்கள்",
  test: "சோதனை அறிவிப்பைக் காட்டு",
  testMessage: "இது ஒரு சோதனை உதவி அறிவிப்பு.",
  notificationHint:
    "செயலியில் அறிவிப்பு விருப்பங்களை இங்கே சேமிக்கவும். அறிவிப்புகளை அனுப்பும் வசதியைக் குழு பின்னர் இணைக்கலாம். சோதனை பொத்தானைப் பயன்படுத்தி அறிவிப்பைப் பார்க்கவும்.",
  account: "கணக்கு அமைப்புகள்",
  accountHint: "கணக்கு அம்சங்கள் கணக்குக் குழுவால் சேர்க்கப்படும்.",
  reset: "அமைப்புகளை மீட்டமை",
  resetQuestion: "இயல்புநிலை அமைப்புகளை மீட்டமைக்கவா?",
  cancel: "ரத்து",
  restore: "இயல்புநிலைக்கு மீட்டமை",
  saved: "இந்த உலாவியில் தானாகச் சேமிக்கப்படும்.",
  storageError:
    "உலாவி சேமிப்பகம் கிடைக்கவில்லை. மாற்றங்கள் இந்த அமர்வுக்கு மட்டுமே பொருந்தும்.",
  home: "முகப்பு",
  trail: "கண்டுபிடிப்புப் பாதை",
  chatbot: "உரையாடல் உதவியாளர்",
  help: "உதவி",
  resetSaved: "அமைப்புகள் மீட்டமைக்கப்பட்டன.",
  accountPlaceholder: "கணக்கு அமைப்புகள் — விரைவில்",
};
export const settingsStrings = { en, zh, ms, ta };
export function getSettingsStrings(language: ChatLanguage) {
  return settingsStrings[language];
}
