import type { ChatLanguage } from "../../types/help";

export type VisitorStringDictionary = Readonly<Record<string, string>>;

const en: VisitorStringDictionary = {};

const zh: VisitorStringDictionary = {
  "Home": "首页", "Discovery Trail": "探索路线", "Toy Game": "玩具游戏", "Rewards": "奖励",
  "Chatbot": "聊天机器人", "Contact": "联系我们", "Settings": "设置", "Help": "帮助",
  "Visitor": "访客", "MINTH home": "MINTH 首页", "MINTH Adventure Guide": "MINTH 探险指南",
  "Museum of Toys home": "玩具博物馆首页", "Footer": "页脚", "Privacy Policy": "隐私政策",
  "Terms and Conditions": "条款与条件", "Media": "媒体", "©": "©",
  "All Rights Reserved.": "版权所有。",
  "Visitor Home": "访客首页", "Choose the map, explore the Discovery Trail, or play a toy game.": "选择地图、探索路线，或玩一场玩具游戏。",
  "Museum Map": "博物馆地图", "Browse exhibits freely, and optionally get directions after scanning a QR code.": "自由浏览展品，也可扫描二维码获取路线指引。",
  "Open Museum Map →": "打开博物馆地图 →", "A guided trail around the museum is coming soon.": "博物馆导览路线即将推出。",
  "Open Discovery Trail →": "开启探索路线 →", "Play the Toy Time Machine challenge, collect three stamps, and earn 20 points.": "参与玩具时光机挑战，收集三枚印章并获得 20 分。",
  "Map preview": "地图预览", "Discovery Trail preview": "探索路线预览", "🎮 Game preview": "🎮 游戏预览",
  "Open Toy Game →": "开始玩具游戏 →", "Free browsing of the museum's floors and exhibits.": "自由浏览博物馆楼层和展品。",
  "Floor selector (uses src/data/floors.ts)": "楼层选择器（使用 src/data/floors.ts）",
  "Floor map with locations and exhibits (uses src/data/locations.ts and exhibits.ts)": "包含地点和展品的楼层地图（使用 src/data/locations.ts 和 exhibits.ts）",
  "Exhibit details when a location is selected": "选择地点后显示展品详情", "Optional directions after scanning a location QR code": "扫描地点二维码后可选查看路线",
  "Floor selector": "楼层选择器", "Museum floor map": "博物馆楼层地图", "Not built yet": "尚未建立",
  "Directions (after QR scan)": "路线指引（扫描二维码后）", "Planned for this page": "本页面规划内容",
  "Trail routes and stops will appear here.": "路线和站点将在此处显示。",
  "Profile": "个人资料", "Your visitor details and game progress.": "访客资料和游戏进度。",
  "Demo account · Saved on this browser": "演示账户 · 保存在此浏览器",
  "Browser storage is unavailable. Your demo balance and progress may not save.": "浏览器存储不可用。演示余额和进度可能无法保存。",
  "TOY TIME MACHINE": "玩具时光机", "Game progress": "游戏进度", "stamps collected": "枚印章已收集",
  "Game missions completed": "已完成的游戏任务", "points earned": "已获得积分",
  "You already earned the one-time {points}-point game bonus. Restarting the game does not earn more points.": "你已获得一次性 {points} 分游戏奖励。重新开始游戏不会获得更多积分。",
  "Complete all three missions to earn {points} points.": "完成全部三个任务即可获得 {points} 分。",
  "Collected mission stamps": "已收集的任务印章", "View completed game →": "查看已完成的游戏 →",
  "Continue Toy Game →": "继续玩具游戏 →", "Browse rewards": "浏览奖励", "READY FOR YOUR NEXT ADVENTURE": "准备好开启下一场冒险",
  "Available points": "可用积分", "Browse rewards →": "浏览奖励 →",
  "TOY GAME · OUTERSPACE DEMO": "玩具游戏 · 外太空演示", "The Toy Time Machine": "玩具时光机",
  "Three dials have stopped working: Launch, Direction, and Home. Find the toys and solve their clues to restore them.": "三个旋钮停止运作：启动、方向和返回。找到玩具并解开线索，让它们恢复运作。",
  "Your trail progress": "你的探索进度", "stamps": "枚印章", "One stamp per finished mission": "每完成一个任务获得一枚印章",
  "One-time game completion bonus": "一次性游戏完成奖励", "available": "可用", "Choose rewards to spend points": "选择奖励并使用积分",
  "Mission stamps": "任务印章", "MISSION {mission} / 3 · CLUE {clue} / {total}": "任务 {mission} / 3 · 线索 {clue} / {total}",
  "Choose one answer": "选择一个答案", "Exhibit QR code": "展品二维码", "Toy name": "玩具名称",
  "Missing word": "缺失的词语", "Check answer": "检查答案", "Demo scan controls": "演示扫描控制",
  "Scan the correct toy": "扫描正确的玩具", "Scan a different toy": "扫描其他玩具",
  "View demo exhibit information": "查看展品演示信息", "This is fictional demo content, not a museum exhibit.": "这是虚构的演示内容，并非博物馆展品。",
  "Facts from ": "资料来源：", "MINT’s Outerspace collection": "MINT 外太空藏品", ". Physical display wording has not been checked.": "。实体展品说明尚未核实。",
  "Demo illustration": "演示插图", "Image: MINT Museum of Toys": "图片：MINT 玩具博物馆",
  "Toy photo unavailable": "玩具照片无法显示", "Use the exhibit information below to continue.": "请参考下方展品信息继续。",
  "MISSION COMPLETE": "任务完成", "The Toy Time Machine is restored!": "玩具时光机已修复！",
  "Adventure complete! Your one-time {points}-point game bonus is saved. Choose your reward.": "冒险完成！一次性 {points} 分游戏奖励已保存。选择你的奖励。",
  "Adventure complete! You earned {points} points. Choose your reward.": "冒险完成！你获得了 {points} 分。选择你的奖励。",
  "This game offers a one-time total of {points} points. Replaying will not earn more.": "本游戏一次最多可获得 {points} 分。重新游玩不会获得更多积分。",
  "This prototype uses sample QR codes and browser saved progress. Museum photos, physical placements, label wording, and real reward rules still need approval.": "此原型使用示例二维码并将进度保存在浏览器中。博物馆照片、实体摆放位置、标签文字及实际奖励规则仍待批准。",
  "Restart demo": "重新开始演示", "Demo restarted. Your points and reward history stay saved, and this game bonus can only be earned once.": "演示已重新开始。积分和奖励记录仍会保留，游戏奖励只能获得一次。",
  "That code belongs to another toy. Keep looking.": "此二维码属于其他玩具。请继续寻找。",
  "Not quite. Check the toy information and try again.": "还不正确。查看玩具信息后再试一次。",
  "We could not save your game progress in this browser. Check browser storage and try again.": "无法在此浏览器保存游戏进度。请检查浏览器存储后重试。",
  "This question needs a written answer. Scanning cannot skip it.": "此题需要填写答案，扫描不能跳过。",
  "Stamp collected! ": "已收集印章！", "We could not save the restarted game in this browser. Check browser storage and try again.": "无法在此浏览器保存重新开始的游戏。请检查浏览器存储后重试。",
  "Choose a treat for your adventure. These rewards are demo proposals only.": "为你的冒险挑选一份礼物。这些奖励仅为演示提案。",
  "The Toy Time Machine offers a one-time total of 20 points after all three missions are complete. Replaying the game will not earn more points. Reward costs and stock are demo settings; real rewards require secure server validation.": "完成全部三个任务后，玩具时光机一次性提供共 20 分。重新游玩不会获得更多积分。奖励积分和库存为演示设置；真实奖励需通过安全服务器验证。",
  "Browser storage is unavailable. Progress and rewards may not save; redemptions are disabled until storage is available.": "浏览器存储不可用。进度和奖励可能无法保存；存储恢复前无法兑换。",
  "Choose a reward": "选择奖励", "points": "积分", "Out of stock": "缺货",
  "{stock} available (demo stock)": "剩余 {stock} 份（演示库存）", "Demo only · no voucher code issued": "仅供演示 · 不会签发优惠券代码",
  "You need {points} more points": "还需要 {points} 分", "Redeem": "兑换", "My rewards": "我的奖励",
  "No rewards yet. Choose one above when you’re ready!": "目前没有奖励。准备好后，请从上方选择一项！",
  "Demo-only reference: {id}": "仅供演示的参考编号：{id}", "Ready to use": "可使用", "Used": "已使用",
  "In a live service, only authorised staff can mark a reward as used. No visitor-side status controls are available in this demo.": "正式服务中，只有获授权的工作人员可以将奖励标记为已使用。本演示不提供访客端状态控制。",
  "Points activity": "积分记录", "Complete all three Toy Time Machine missions to earn 20 points.": "完成玩具时光机的全部三个任务即可获得 20 分。",
  "Back to Profile": "返回个人资料", "View Toy Time Machine": "查看玩具时光机", "CONFIRM REDEMPTION · DEMO": "确认兑换 · 演示",
  "Cost:": "所需积分：", "After redemption:": "兑换后：", "points remaining": "剩余积分",
  "Terms:": "条款：", "This is a demo proposal, not a real voucher or an official FairPrice partnership. No voucher code will be created.": "此为演示提案，并非真实优惠券或 FairPrice 官方合作。不会创建优惠券代码。",
  "Cancel": "取消", "Confirm redemption": "确认兑换", "You need {points} more points.": "还需要 {points} 分。",
  "Please choose another reward.": "请选择其他奖励。", "This reward is no longer available.": "此奖励已不可用。",
  "We could not save this redemption on this browser. No points were deducted; please check your browser storage and try again.": "无法在此浏览器保存兑换记录。未扣除积分；请检查浏览器存储后重试。",
  "Reward reserved! Your demo-only reference is {id}.": "奖励已预留！仅供演示的参考编号为 {id}。",
  "Contact MINTH": "联系 MINTH", "Every great adventure starts with a hello.": "每一场精彩冒险都从问候开始。",
  "LET'S TALK": "聊一聊", "Drop us a message": "给我们留言", "Have a question about your visit? We'd love to hear from you.": "对参观有疑问吗？欢迎联系我们。",
  "Your name": "姓名", "How should we address you?": "我们该如何称呼你？", "Email address": "电子邮件地址",
  "Subject": "主题", "What would you like to know?": "你想了解什么？", "Your message": "留言内容",
  "Tell us how we can help...": "请告诉我们如何为你提供帮助……", "Open email draft": "打开电子邮件草稿",
  "Opens your email app with your message ready to send.": "打开电子邮件应用，你的留言将准备好发送。",
  "COME SAY HELLO": "欢迎来访", "A little wonder, right on Seah Street.": "就在 Seah Street，邂逅一份奇妙。",
  "Find us in the heart of Singapore. Plan your visit or get in touch below.": "我们位于新加坡中心。请规划行程或通过下方方式联系我们。",
  "Get directions": "获取路线", "(opens in a new tab)": "（在新标签页中打开）",
  "A world of toys. A lifetime of memories.": "玩具的世界，一生的回忆。",
  "Museum Chatbot": "博物馆聊天机器人", "I can answer questions about MINT. I may not know everything. For other help, ask a staff member.": "我可以回答有关 MINT 的问题，但不一定无所不知。如需其他帮助，请咨询工作人员。",
  "Page buttons and labels in Chinese, Malay and Tamil (needs the language setting)": "中文、马来语和泰米尔语的页面按钮及标签（需设置语言）",
  "Hand over to a staff member (human in the loop)": "转交工作人员处理（人工协助）",
  "MINT evacuation steps and assembly point (waiting for MINT to supply them)": "MINT 疏散步骤和集合点（等待 MINT 提供）",
  "Frequently asked questions": "常见问题", "How to use the Museum Map and Discovery Trail": "如何使用博物馆地图和探索路线",
  "FAQ": "常见问题",
  "Contacting Us About Your Personal Information": "联系我们咨询个人信息", "You may contact us to:": "你可以联系我们以：",
  "Request access to personal information we hold about you and information about how it has been used or disclosed, subject to applicable law.": "在适用法律允许的范围内，申请查阅我们持有的你的个人信息，以及这些信息的使用或披露方式。",
  "Request correction of inaccurate or incomplete personal information.": "申请更正不准确或不完整的个人信息。",
  "Withdraw consent to future collection, use, or disclosure where processing relies on your consent.": "当处理基于你的同意时，撤回对未来收集、使用或披露的同意。",
  "Ask questions or raise a concern about our privacy practices.": "询问或提出有关我们隐私做法的疑虑。",
  "We will respond in accordance with applicable legal requirements. We may need to verify your identity before acting on a request.": "我们将按照适用法律要求作出回应。处理请求前，我们可能需要核实你的身份。",
  "If withdrawing consent affects our ability to provide a particular feature, we will explain the consequences. Withdrawal does not affect processing already carried out or processing permitted or required by law.": "如果撤回同意会影响我们提供某项功能的能力，我们会说明其后果。撤回不会影响已经进行的处理，也不会影响法律允许或要求的处理。",
  "9. Younger Visitors": "9. 年轻访客", "We encourage younger visitors to involve a parent or guardian before submitting personal information through MINTH.": "我们鼓励年轻访客在通过 MINTH 提交个人信息前，先咨询父母或监护人。",
  "If you believe a child has provided information that should not have been collected, please contact us so we can review and address the situation.": "如果你认为儿童提供了不应收集的信息，请联系我们，以便我们审查并处理。",
  "10. External Websites": "10. 外部网站", "11. Changes to This Policy": "11. 本政策的变更", "12. Contact Us": "12. 联系我们",
  "MINTH may contain links to websites operated by museums, ticketing providers, or other organisations. This Privacy Policy applies only to MINTH.": "MINTH 可能包含博物馆、票务服务商或其他机构运营网站的链接。本隐私政策仅适用于 MINTH。",
  "Please review the privacy policy of an external website before sharing information with it.": "向外部网站提供信息前，请先查阅其隐私政策。",
  "We may update this Privacy Policy as our website or data practices change. The latest version will be available on this page with an updated date.": "随着网站或数据处理方式的变化，我们可能更新本隐私政策。最新版本及更新日期将在本页面公布。",
  "Where changes involve new uses of personal information, we will provide notice and obtain further consent where required by law.": "如变更涉及个人信息的新用途，我们将在适用法律要求时发出通知并征求进一步同意。",
  "If you have questions, requests, or concerns about your personal information, please contact our privacy representative.": "如对个人信息有疑问、请求或疑虑，请联系隐私事务代表。",
  "Thank you for visiting MINTH.": "感谢你访问 MINTH。",
  "MINTH Terms & Conditions": "MINTH 条款与条件", "Last updated:": "最后更新：",
  "Welcome to MINTH. We hope our museum guide helps you enjoy discovering the stories behind the exhibits.": "欢迎来到 MINTH。希望本博物馆指南能帮助你探索展品背后的故事，享受参观体验。",
  "1. Using MINTH": "1. 使用 MINTH", "2. Your Museum Guide": "2. 博物馆指南", "3. Content, Images, and Trademarks": "3. 内容、图片和商标",
  "4. Links to Other Websites": "4. 其他网站链接", "5. Tickets and Bookings": "5. 门票和预订", "6. Your Privacy": "6. 你的隐私",
  "7. Website Availability": "7. 网站可用性", "8. Our Responsibility": "8. 我们的责任", "9. Updates to MINTH and These Terms": "9. MINTH 和本条款的更新",
  "10. Protecting the Website": "10. 网站保护", "11. Additional Terms": "11. 附加条款", "12. If Part of These Terms Cannot Apply": "12. 条款部分无效时",
  "13. Governing Law": "13. 适用法律", "14. Contact Us": "14. 联系我们",
};

const ms: VisitorStringDictionary = {
  "Home": "Laman Utama", "Discovery Trail": "Jejak Penerokaan", "Toy Game": "Permainan Mainan", "Rewards": "Ganjaran",
  "Chatbot": "Chatbot", "Contact": "Hubungi Kami", "Settings": "Tetapan", "Help": "Bantuan",
  "Visitor": "Pelawat", "MINTH home": "Laman utama MINTH", "MINTH Adventure Guide": "Panduan Pengembaraan MINTH",
  "Museum of Toys home": "Laman utama Muzium Mainan", "Footer": "Pengaki", "Privacy Policy": "Dasar Privasi",
  "Terms and Conditions": "Terma dan Syarat", "Media": "Media", "All Rights Reserved.": "Hak Cipta Terpelihara.",
  "Visitor Home": "Laman Utama Pelawat", "Choose the map, explore the Discovery Trail, or play a toy game.": "Pilih peta, terokai Jejak Penerokaan atau main permainan mainan.",
  "Museum Map": "Peta Muzium", "Browse exhibits freely, and optionally get directions after scanning a QR code.": "Terokai pameran dengan bebas dan dapatkan arah selepas mengimbas kod QR jika perlu.",
  "Open Museum Map →": "Buka Peta Muzium →", "A guided trail around the museum is coming soon.": "Jejak berpandu di sekitar muzium akan tersedia tidak lama lagi.",
  "Open Discovery Trail →": "Buka Jejak Penerokaan →", "Play the Toy Time Machine challenge, collect three stamps, and earn 20 points.": "Main cabaran Mesin Masa Mainan, kumpul tiga cop dan dapatkan 20 mata.",
  "Map preview": "Pratonton peta", "Discovery Trail preview": "Pratonton Jejak Penerokaan", "🎮 Game preview": "🎮 Pratonton permainan",
  "Open Toy Game →": "Buka Permainan Mainan →", "Free browsing of the museum's floors and exhibits.": "Terokai tingkat dan pameran muzium dengan bebas.",
  "Floor selector": "Pemilih tingkat", "Museum floor map": "Peta tingkat muzium", "Not built yet": "Belum dibangunkan", "Planned for this page": "Perancangan halaman ini",
  "Directions (after QR scan)": "Arah (selepas imbasan QR)", "Trail routes and stops will appear here.": "Laluan dan hentian akan dipaparkan di sini.",
  "Profile": "Profil", "Your visitor details and game progress.": "Maklumat pelawat dan kemajuan permainan anda.",
  "Demo account · Saved on this browser": "Akaun demo · Disimpan dalam pelayar ini",
  "Browser storage is unavailable. Your demo balance and progress may not save.": "Storan pelayar tidak tersedia. Baki demo dan kemajuan anda mungkin tidak disimpan.",
  "TOY TIME MACHINE": "MESIN MASA MAINAN", "Game progress": "Kemajuan permainan", "stamps collected": "cop dikumpulkan",
  "Game missions completed": "Misi permainan selesai", "points earned": "mata diperoleh", "Collected mission stamps": "Cop misi dikumpulkan",
  "View completed game →": "Lihat permainan yang selesai →", "Continue Toy Game →": "Teruskan Permainan Mainan →", "Browse rewards": "Lihat ganjaran",
  "Available points": "Mata tersedia", "Browse rewards →": "Lihat ganjaran →",
  "TOY GAME · OUTERSPACE DEMO": "PERMAINAN MAINAN · DEMO ANGKASA LEPAS", "The Toy Time Machine": "Mesin Masa Mainan",
  "Three dials have stopped working: Launch, Direction, and Home. Find the toys and solve their clues to restore them.": "Tiga dail telah berhenti berfungsi: Pelancaran, Arah dan Pulang. Cari mainan dan selesaikan petunjuk untuk memulihkannya.",
  "Your trail progress": "Kemajuan jejak anda", "One stamp per finished mission": "Satu cop bagi setiap misi yang selesai",
  "One-time game completion bonus": "Bonus tamat permainan sekali sahaja", "available": "tersedia", "Choose rewards to spend points": "Pilih ganjaran untuk menggunakan mata",
  "Choose one answer": "Pilih satu jawapan", "Exhibit QR code": "Kod QR pameran", "Toy name": "Nama mainan", "Missing word": "Perkataan yang hilang",
  "Check answer": "Semak jawapan", "Demo scan controls": "Kawalan imbasan demo", "Scan the correct toy": "Imbas mainan yang betul",
  "Scan a different toy": "Imbas mainan lain", "View demo exhibit information": "Lihat maklumat pameran demo",
  "This is fictional demo content, not a museum exhibit.": "Ini kandungan demo fiksyen, bukan pameran muzium.",
  "Demo illustration": "Ilustrasi demo", "Image: MINT Museum of Toys": "Imej: MINT Museum of Toys",
  "Toy photo unavailable": "Foto mainan tidak tersedia", "Use the exhibit information below to continue.": "Gunakan maklumat pameran di bawah untuk meneruskan.",
  "MISSION COMPLETE": "MISI SELESAI", "The Toy Time Machine is restored!": "Mesin Masa Mainan telah dipulihkan!",
  "Restart demo": "Mulakan semula demo", "That code belongs to another toy. Keep looking.": "Kod itu milik mainan lain. Teruskan mencari.",
  "Not quite. Check the toy information and try again.": "Belum tepat. Semak maklumat mainan dan cuba lagi.",
  "Correct! Next clue unlocked.": "Betul! Petunjuk seterusnya dibuka.",
  "Choose a treat for your adventure. These rewards are demo proposals only.": "Pilih hadiah untuk pengembaraan anda. Ganjaran ini hanya cadangan demo.",
  "Choose a reward": "Pilih ganjaran", "points": "mata", "Out of stock": "Kehabisan stok", "Redeem": "Tebus",
  "My rewards": "Ganjaran saya", "Points activity": "Aktiviti mata", "Back to Profile": "Kembali ke Profil",
  "View Toy Time Machine": "Lihat Mesin Masa Mainan", "CONFIRM REDEMPTION · DEMO": "SAHKAN PENEBUSAN · DEMO",
  "Cost:": "Kos:", "After redemption:": "Selepas penebusan:", "Terms:": "Terma:", "Cancel": "Batal", "Confirm redemption": "Sahkan penebusan",
  "Contact MINTH": "Hubungi MINTH", "Every great adventure starts with a hello.": "Setiap pengembaraan hebat bermula dengan sapaan.",
  "LET'S TALK": "MARI BERBUAL", "Drop us a message": "Hantarkan mesej kepada kami",
  "Your name": "Nama anda", "Email address": "Alamat e-mel", "Subject": "Subjek", "Your message": "Mesej anda",
  "Open email draft": "Buka draf e-mel", "COME SAY HELLO": "JOM KUNJUNGI KAMI", "Get directions": "Dapatkan arah",
  "A world of toys. A lifetime of memories.": "Dunia mainan. Kenangan sepanjang hayat.",
  "Museum Chatbot": "Chatbot Muzium", "Frequently asked questions": "Soalan lazim", "FAQ": "Soalan lazim",
  "Contacting Us About Your Personal Information": "Menghubungi Kami tentang Maklumat Peribadi Anda",
  "You may contact us to:": "Anda boleh menghubungi kami untuk:", "Request correction of inaccurate or incomplete personal information.": "Memohon pembetulan maklumat peribadi yang tidak tepat atau tidak lengkap.",
  "9. Younger Visitors": "9. Pelawat Muda", "10. External Websites": "10. Laman Web Luaran",
  "11. Changes to This Policy": "11. Perubahan kepada Dasar Ini", "12. Contact Us": "12. Hubungi Kami",
  "Thank you for visiting MINTH.": "Terima kasih kerana melawat MINTH.", "MINTH Terms & Conditions": "Terma & Syarat MINTH",
};

const ta: VisitorStringDictionary = {
  "Home": "முகப்பு", "Discovery Trail": "ஆய்வுப் பாதை", "Toy Game": "பொம்மை விளையாட்டு", "Rewards": "வெகுமதிகள்",
  "Chatbot": "உரையாடல் உதவியாளர்", "Contact": "தொடர்பு", "Settings": "அமைப்புகள்", "Help": "உதவி",
  "Visitor": "வருகையாளர்", "MINTH home": "MINTH முகப்பு", "MINTH Adventure Guide": "MINTH சாகச வழிகாட்டி",
  "Museum of Toys home": "பொம்மை அருங்காட்சியக முகப்பு", "Footer": "அடிக்குறிப்பு", "Privacy Policy": "தனியுரிமைக் கொள்கை",
  "Terms and Conditions": "விதிமுறைகள் மற்றும் நிபந்தனைகள்", "Media": "ஊடகம்", "All Rights Reserved.": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
  "Visitor Home": "வருகையாளர் முகப்பு", "Choose the map, explore the Discovery Trail, or play a toy game.": "வரைபடத்தைத் தேர்ந்தெடுத்து, ஆய்வுப் பாதையை ஆராயுங்கள் அல்லது பொம்மை விளையாட்டை விளையாடுங்கள்.",
  "Museum Map": "அருங்காட்சியக வரைபடம்", "Browse exhibits freely, and optionally get directions after scanning a QR code.": "காட்சிப்பொருட்களைத் தாராளமாகப் பாருங்கள்; QR குறியீட்டை ஸ்கேன் செய்தபின் வழியையும் பெறலாம்.",
  "Open Museum Map →": "அருங்காட்சியக வரைபடத்தைத் திற →", "A guided trail around the museum is coming soon.": "அருங்காட்சியக வழிகாட்டிப் பாதை விரைவில் வருகிறது.",
  "Open Discovery Trail →": "ஆய்வுப் பாதையைத் திற →", "Play the Toy Time Machine challenge, collect three stamps, and earn 20 points.": "பொம்மை கால இயந்திரச் சவாலை விளையாடி, மூன்று முத்திரைகளைச் சேகரித்து 20 புள்ளிகளைப் பெறுங்கள்.",
  "Map preview": "வரைபட முன்னோட்டம்", "Discovery Trail preview": "ஆய்வுப் பாதை முன்னோட்டம்", "🎮 Game preview": "🎮 விளையாட்டு முன்னோட்டம்",
  "Open Toy Game →": "பொம்மை விளையாட்டைத் திற →", "Free browsing of the museum's floors and exhibits.": "அருங்காட்சியகத் தளங்களையும் காட்சிப்பொருட்களையும் சுதந்திரமாகப் பாருங்கள்.",
  "Floor selector": "தளத் தேர்வி", "Museum floor map": "அருங்காட்சியகத் தள வரைபடம்", "Not built yet": "இன்னும் உருவாக்கப்படவில்லை", "Planned for this page": "இந்தப் பக்கத்திற்கான திட்டம்",
  "Directions (after QR scan)": "வழிகள் (QR ஸ்கேன் செய்தபின்)", "Trail routes and stops will appear here.": "பாதைகளும் நிறுத்தங்களும் இங்கே தோன்றும்.",
  "Profile": "சுயவிவரம்", "Your visitor details and game progress.": "உங்கள் வருகையாளர் விவரங்களும் விளையாட்டு முன்னேற்றமும்.",
  "Demo account · Saved on this browser": "டெமோ கணக்கு · இந்த உலாவியில் சேமிக்கப்பட்டது",
  "Browser storage is unavailable. Your demo balance and progress may not save.": "உலாவி சேமிப்பகம் கிடைக்கவில்லை. டெமோ இருப்பும் முன்னேற்றமும் சேமிக்கப்படாமல் இருக்கலாம்.",
  "TOY TIME MACHINE": "பொம்மை கால இயந்திரம்", "Game progress": "விளையாட்டு முன்னேற்றம்", "stamps collected": "முத்திரைகள் சேகரிக்கப்பட்டன",
  "Game missions completed": "நிறைவு செய்த விளையாட்டுப் பணிகள்", "points earned": "புள்ளிகள் பெற்றது", "Collected mission stamps": "சேகரித்த பணி முத்திரைகள்",
  "View completed game →": "நிறைவு செய்த விளையாட்டைப் பார் →", "Continue Toy Game →": "பொம்மை விளையாட்டைத் தொடரவும் →", "Browse rewards": "வெகுமதிகளைப் பாருங்கள்",
  "Available points": "கிடைக்கும் புள்ளிகள்", "Browse rewards →": "வெகுமதிகளைப் பாருங்கள் →",
  "TOY GAME · OUTERSPACE DEMO": "பொம்மை விளையாட்டு · விண்வெளி டெமோ", "The Toy Time Machine": "பொம்மை கால இயந்திரம்",
  "Three dials have stopped working: Launch, Direction, and Home. Find the toys and solve their clues to restore them.": "தொடக்கம், திசை, வீடு ஆகிய மூன்று டயல்களும் செயலிழந்தன. பொம்மைகளைக் கண்டுபிடித்து குறிப்புகளைத் தீர்த்து அவற்றைச் சரிசெய்யுங்கள்.",
  "Your trail progress": "உங்கள் பாதை முன்னேற்றம்", "One stamp per finished mission": "நிறைவு செய்யும் ஒவ்வொரு பணிக்கும் ஒரு முத்திரை",
  "One-time game completion bonus": "ஒருமுறை மட்டும் கிடைக்கும் விளையாட்டு நிறைவு போனஸ்", "available": "கிடைக்கும்", "Choose rewards to spend points": "புள்ளிகளைப் பயன்படுத்த வெகுமதிகளைத் தேர்ந்தெடுங்கள்",
  "Choose one answer": "ஒரு பதிலைத் தேர்ந்தெடுக்கவும்", "Exhibit QR code": "காட்சிப்பொருள் QR குறியீடு", "Toy name": "பொம்மையின் பெயர்", "Missing word": "விடுபட்ட சொல்",
  "Check answer": "பதிலைச் சரிபார்க்கவும்", "Demo scan controls": "டெமோ ஸ்கேன் கட்டுப்பாடுகள்", "Scan the correct toy": "சரியான பொம்மையை ஸ்கேன் செய்யவும்",
  "Scan a different toy": "வேறொரு பொம்மையை ஸ்கேன் செய்யவும்", "View demo exhibit information": "டெமோ காட்சிப்பொருள் தகவலைப் பார்க்கவும்",
  "This is fictional demo content, not a museum exhibit.": "இது கற்பனையான டெமோ உள்ளடக்கம்; அருங்காட்சியகக் காட்சிப்பொருள் அல்ல.",
  "Demo illustration": "டெமோ விளக்கப்படம்", "Image: MINT Museum of Toys": "படம்: MINT பொம்மை அருங்காட்சியகம்",
  "Toy photo unavailable": "பொம்மைப் படம் கிடைக்கவில்லை", "Use the exhibit information below to continue.": "தொடர கீழே உள்ள காட்சிப்பொருள் தகவலைப் பயன்படுத்துங்கள்.",
  "MISSION COMPLETE": "பணி நிறைவு", "The Toy Time Machine is restored!": "பொம்மை கால இயந்திரம் சரிசெய்யப்பட்டது!",
  "Restart demo": "டெமோவை மறுதொடக்கம் செய்", "That code belongs to another toy. Keep looking.": "அந்தக் குறியீடு வேறொரு பொம்மைக்குரியது. தொடர்ந்து தேடுங்கள்.",
  "Not quite. Check the toy information and try again.": "சரியில்லை. பொம்மைத் தகவலைப் பார்த்து மீண்டும் முயற்சிக்கவும்.",
  "Correct! Next clue unlocked.": "சரி! அடுத்த குறிப்பு திறக்கப்பட்டது.",
  "Choose a treat for your adventure. These rewards are demo proposals only.": "உங்கள் சாகசத்திற்கான பரிசைத் தேர்ந்தெடுங்கள். இவை டெமோ பரிந்துரைகள் மட்டுமே.",
  "Choose a reward": "வெகுமதியைத் தேர்ந்தெடுக்கவும்", "points": "புள்ளிகள்", "Out of stock": "இருப்பு இல்லை", "Redeem": "பெறுக",
  "My rewards": "எனது வெகுமதிகள்", "Points activity": "புள்ளி செயல்பாடு", "Back to Profile": "சுயவிவரத்திற்குத் திரும்பு",
  "View Toy Time Machine": "பொம்மை கால இயந்திரத்தைப் பார்", "CONFIRM REDEMPTION · DEMO": "பெறுதலை உறுதிப்படுத்து · டெமோ",
  "Cost:": "செலவு:", "After redemption:": "பெற்ற பிறகு:", "Terms:": "விதிமுறைகள்:", "Cancel": "ரத்து செய்", "Confirm redemption": "பெறுதலை உறுதிப்படுத்து",
  "Contact MINTH": "MINTH-ஐத் தொடர்புகொள்ளவும்", "Every great adventure starts with a hello.": "ஒவ்வொரு சிறந்த சாகசமும் ஒரு வணக்கத்துடன் தொடங்குகிறது.",
  "LET'S TALK": "பேசுவோம்", "Drop us a message": "எங்களுக்கு ஒரு செய்தி அனுப்புங்கள்", "Your name": "உங்கள் பெயர்",
  "Email address": "மின்னஞ்சல் முகவரி", "Subject": "பொருள்", "Your message": "உங்கள் செய்தி", "Open email draft": "மின்னஞ்சல் வரைவைத் திற",
  "COME SAY HELLO": "வந்து வணக்கம் சொல்லுங்கள்", "Get directions": "வழியைப் பெறுங்கள்",
  "A world of toys. A lifetime of memories.": "பொம்மைகளின் உலகம். வாழ்நாள் நினைவுகள்.",
  "Museum Chatbot": "அருங்காட்சியக உரையாடல் உதவியாளர்", "Frequently asked questions": "அடிக்கடி கேட்கப்படும் கேள்விகள்", "FAQ": "கேள்விகள்",
  "Contacting Us About Your Personal Information": "உங்கள் தனிப்பட்ட தகவல் குறித்து எங்களைத் தொடர்புகொள்வது",
  "You may contact us to:": "பின்வரும் தேவைகளுக்காக எங்களைத் தொடர்புகொள்ளலாம்:", "Request correction of inaccurate or incomplete personal information.": "தவறான அல்லது முழுமையற்ற தனிப்பட்ட தகவலைத் திருத்தக் கோருங்கள்.",
  "9. Younger Visitors": "9. இளம் பார்வையாளர்கள்", "10. External Websites": "10. வெளிப்புற இணையதளங்கள்",
  "11. Changes to This Policy": "11. இந்தக் கொள்கையில் மாற்றங்கள்", "12. Contact Us": "12. எங்களைத் தொடர்புகொள்ளவும்",
  "Thank you for visiting MINTH.": "MINTH-ஐப் பார்வையிட்டதற்கு நன்றி.", "MINTH Terms & Conditions": "MINTH விதிமுறைகள் மற்றும் நிபந்தனைகள்",
};

export type VisitorStrings = VisitorStringDictionary;

const zhExtended: VisitorStringDictionary = {
  "Profile: {name}": "个人资料：{name}",
  "Find the Moon Rocket XM-12 and scan its code.": "找到 Moon Rocket XM-12 并扫描其代码。",
  "What is the name of this toy?": "这件玩具叫什么名字？", "Fill in the missing fact.": "补全缺失的信息。",
  "The Moon Rocket XM-12 was made in ____.": "Moon Rocket XM-12 制造于____。",
  "Which company made the Moon Rocket XM-12?": "哪家公司制造了 Moon Rocket XM-12？",
  "Find the Robot Action Dalek and scan its code.": "找到 Robot Action Dalek 并扫描其代码。",
  "The Robot Action Dalek dates to around ____.": "Robot Action Dalek 大约可追溯至____年。",
  "What color was the museum's battery Dalek?": "博物馆的电池驱动 Dalek 是什么颜色？",
  "Find the Lone Star Aqua Jet and scan its code.": "找到 Lone Star Aqua Jet 并扫描其代码。",
  "The Aqua Jet was first released as the ____.": "Aqua Jet 最初以____名称发行。",
  "Which company made the Lone Star Aqua Jet?": "哪家公司制造了 Lone Star Aqua Jet？",
  "Find the Demo Comet Rover and scan its code.": "找到演示 Comet Rover 并扫描其代码。",
  "What is the name of this demo toy?": "这件演示玩具叫什么名字？", "Fill in the missing demo fact.": "补全缺失的演示信息。",
  "The Demo Comet Rover has ____ wheels.": "演示 Comet Rover 有____个轮子。",
  "How many wheels does the Demo Comet Rover have?": "演示 Comet Rover 有多少个轮子？",
  "Find the Demo Orbit Scout Ship and scan its code.": "找到演示 Orbit Scout Ship 并扫描其代码。",
  "The Demo Orbit Scout Ship carries ____ astronauts.": "演示 Orbit Scout Ship 搭载____名宇航员。",
  "What color are the Demo Orbit Scout Ship's wings?": "演示 Orbit Scout Ship 的机翼是什么颜色？",
  "Restore the launch dial.": "修复启动旋钮。", "The Toy Time Machine is silent. Solve five toy clues to bring back its power.": "玩具时光机没有声音。解开五条玩具线索，恢复它的动力。",
  "The launch dial glows again. The machine can start!": "启动旋钮再次亮起。机器可以启动了！",
  "Restore the direction dial.": "修复方向旋钮。", "The machine has power, but it needs a direction. Solve five more toy clues.": "机器已有动力，但还需要方向。再解开五条玩具线索。",
  "The direction dial is set. One more dial to go!": "方向旋钮已设置完成！还剩一个旋钮！",
  "Restore the home dial.": "修复返回旋钮。", "The final dial will let the toys return home. Solve the last five toy clues.": "最后一个旋钮将让玩具回家。解开最后五条玩具线索。",
  "All three dials are restored. The Toy Time Machine is ready!": "三个旋钮全部修复。玩具时光机准备就绪！",
  "Launch Stamp": "启动印章", "Direction Stamp": "方向印章", "Home Stamp": "返回印章",
  "Moon Rocket XM-12": "月球火箭 XM-12", "Demo Comet Rover": "演示彗星漫游车", "Demo Orbit Scout Ship": "演示轨道侦察飞船",
  "Conversation": "对话", "You": "你", "MINT Guide": "MINT 指南",
  "Hi! Ask me about opening hours, tickets, what is on each level, or how to get to MINT.": "你好！你可以问我开放时间、门票、各楼层展览，或如何前往 MINT。",
  "You can write in:": "你可以使用以下语言提问：", "Thinking...": "正在思考……", "Quick questions": "快速提问",
  "Tap a question to ask it.": "点击问题即可提问。", "What are your opening hours?": "你们的开放时间是什么？",
  "What is on each level?": "每个楼层有什么展览？", "How can I contact MINT?": "我如何联系 MINT？",
  "Where can I get help?": "我可以在哪里寻求帮助？", "Type your question": "输入你的问题",
  "Press Enter to send. Press Shift and Enter for a new line.": "按 Enter 发送。按 Shift + Enter 换行。",
  "Send": "发送", "Sending...": "正在发送……", "Sorry, I cannot answer right now.": "抱歉，我现在无法回答。",
  "Please check your message and try again.": "请检查你的留言并重试。", "The chatbot is not available at the moment.": "聊天机器人目前无法使用。",
  "Something went wrong on our side.": "我们的系统出现问题。", "We cannot connect. Please check your internet connection.": "无法连接。请检查网络连接。",
  "This took too long.": "等待时间过长。", "The chatbot is not set up yet.": "聊天机器人尚未设置。",
  "The message was cancelled.": "留言已取消。", "You can still get help:": "你仍然可以通过以下方式获得帮助：",
  "Call or WhatsApp": "电话或 WhatsApp", "Email": "电子邮件", "Go to the Help page": "前往帮助页面", "Try again": "重试",
  "Need help now?": "现在需要帮助吗？", "Send a message to museum staff. We do not ask for your name.": "向博物馆工作人员发送消息。我们不会询问你的姓名。",
  "Your message and the area you choose will be shared with museum staff.": "你的消息和所选区域将与博物馆工作人员共享。",
  "In an emergency, tell a staff member now.": "如遇紧急情况，请立即告知工作人员。", "Call": "致电",
  "Where are you?": "你在哪里？", "Choose an area": "选择区域", "Level {level}": "第 {level} 层", "I am not sure": "我不确定",
  "What help do you need?": "你需要什么帮助？", "Send to staff": "发送给工作人员",
  "Your message was not sent": "消息未能发送", "Your message is still in the form.": "消息仍保留在表单中。",
  "Your message was sent to staff": "消息已发送给工作人员", "Reference number": "参考编号", "What to do next": "接下来该怎么做",
  "Safety information": "安全信息", "Stay calm.": "保持冷静。", "If you can, move to a safe place.": "如果可以，请前往安全地点。",
  "Tell a museum staff member.": "告知博物馆工作人员。", "Address": "地址", "Phone or WhatsApp": "电话或 WhatsApp",
  "Opening hours": "开放时间", "Feedback": "意见反馈", "This is optional. It helps us make the guide better.": "此项为选填，可帮助我们改进指南。",
  "How easy was this guide to use?": "这份指南使用起来有多容易？", "Very hard": "非常难", "Hard": "难", "Okay": "一般",
  "Easy": "容易", "Very easy": "非常容易", "Send feedback": "发送反馈", "Thank you for your feedback": "感谢你的反馈",
  "Your feedback helps us improve the guide.": "你的反馈有助于我们改进指南。", "Send more feedback": "再发送反馈",
  "MINT MUSEUM OF TOYS": "MINT 玩具博物馆", "How should we address you?": "我们该如何称呼你？",
  "What would you like to know?": "你想了解什么？", "Tell us how we can help...": "请告诉我们如何为你提供帮助……",
  "Opens your email app with your message ready to send.": "打开电子邮件应用，你的留言将准备好发送。",
  "A little wonder, right on Seah Street.": "就在 Seah Street，邂逅一份奇妙。",
  "Find us in the heart of Singapore. Plan your visit or get in touch below.": "我们位于新加坡中心。请规划行程或通过下方方式联系我们。",
  "Small children’s gift": "儿童小礼物", "20% off one museum admission ticket": "一张博物馆门票八折",
  "S$5 FairPrice voucher (demo proposal)": "5 新元 FairPrice 优惠券（演示提案）",
  "Choose a small surprise such as stickers, a pencil, or a mini activity kit.": "选择一份小惊喜，例如贴纸、铅笔或迷你活动套装。",
  "A proposed demo discount for one museum admission ticket.": "一张博物馆门票的演示折扣提案。",
  "A proposed demo reward only; this is not an issued voucher or an official FairPrice partnership.": "仅为演示奖励提案；这不是已发行的优惠券，也不代表与 FairPrice 官方合作。",
  "Out of stock. Please choose another reward.": "缺货。请选择其他奖励。", "This reward is no longer available.": "此奖励已不可用。",
  "No rewards yet. Choose one above when you’re ready!": "目前没有奖励。准备好后，请从上方选择一项！",
  "Ready to use": "可使用", "Used": "已使用", "Email:": "电子邮件：", "Phone:": "电话：", "Address:": "地址：",
};

const msExtended: VisitorStringDictionary = {
  "Profile: {name}": "Profil: {name}",
  "stamps": "cop", "points remaining": "mata berbaki", "MINT MUSEUM OF TOYS": "MINT MUSEUM OF TOYS",
  "How should we address you?": "Bagaimanakah kami harus memanggil anda?", "What would you like to know?": "Apakah yang ingin anda ketahui?",
  "Tell us how we can help...": "Beritahu kami cara kami boleh membantu...", "Open email draft": "Buka draf e-mel",
  "Opens your email app with your message ready to send.": "Aplikasi e-mel anda akan dibuka dengan mesej yang sedia dihantar.",
  "A little wonder, right on Seah Street.": "Keajaiban kecil di Seah Street.",
  "Find us in the heart of Singapore. Plan your visit or get in touch below.": "Temui kami di tengah Singapura. Rancang lawatan atau hubungi kami di bawah.",
  "Find the Moon Rocket XM-12 and scan its code.": "Cari Moon Rocket XM-12 dan imbas kodnya.",
  "What is the name of this toy?": "Apakah nama mainan ini?", "Fill in the missing fact.": "Lengkapkan fakta yang hilang.",
  "The Moon Rocket XM-12 was made in ____.": "Moon Rocket XM-12 dibuat di ____.",
  "Which company made the Moon Rocket XM-12?": "Syarikat manakah yang membuat Moon Rocket XM-12?",
  "Find the Robot Action Dalek and scan its code.": "Cari Robot Action Dalek dan imbas kodnya.",
  "The Robot Action Dalek dates to around ____.": "Robot Action Dalek berasal sekitar tahun ____.",
  "What color was the museum's battery Dalek?": "Apakah warna Dalek bateri muzium?",
  "Find the Lone Star Aqua Jet and scan its code.": "Cari Lone Star Aqua Jet dan imbas kodnya.",
  "The Aqua Jet was first released as the ____.": "Aqua Jet mula-mula dikeluarkan sebagai ____.",
  "Which company made the Lone Star Aqua Jet?": "Syarikat manakah yang membuat Lone Star Aqua Jet?",
  "Find the Demo Comet Rover and scan its code.": "Cari Demo Comet Rover dan imbas kodnya.",
  "What is the name of this demo toy?": "Apakah nama mainan demo ini?", "Fill in the missing demo fact.": "Lengkapkan fakta demo yang hilang.",
  "The Demo Comet Rover has ____ wheels.": "Demo Comet Rover mempunyai ____ roda.",
  "How many wheels does the Demo Comet Rover have?": "Berapakah jumlah roda Demo Comet Rover?",
  "Find the Demo Orbit Scout Ship and scan its code.": "Cari Demo Orbit Scout Ship dan imbas kodnya.",
  "The Demo Orbit Scout Ship carries ____ astronauts.": "Demo Orbit Scout Ship membawa ____ angkasawan.",
  "What color are the Demo Orbit Scout Ship's wings?": "Apakah warna sayap Demo Orbit Scout Ship?",
  "Restore the launch dial.": "Pulihkan dail pelancaran.", "The Toy Time Machine is silent. Solve five toy clues to bring back its power.": "Mesin Masa Mainan senyap. Selesaikan lima petunjuk mainan untuk menghidupkannya semula.",
  "The launch dial glows again. The machine can start!": "Dail pelancaran bersinar semula. Mesin boleh dimulakan!",
  "Restore the direction dial.": "Pulihkan dail arah.", "The machine has power, but it needs a direction. Solve five more toy clues.": "Mesin mempunyai kuasa tetapi memerlukan arah. Selesaikan lima lagi petunjuk mainan.",
  "The direction dial is set. One more dial to go!": "Dail arah telah ditetapkan. Tinggal satu dail lagi!",
  "Restore the home dial.": "Pulihkan dail pulang.", "The final dial will let the toys return home. Solve the last five toy clues.": "Dail terakhir membolehkan mainan pulang. Selesaikan lima petunjuk terakhir.",
  "All three dials are restored. The Toy Time Machine is ready!": "Ketiga-tiga dail telah dipulihkan. Mesin Masa Mainan sedia digunakan!",
  "Launch Stamp": "Cop Pelancaran", "Direction Stamp": "Cop Arah", "Home Stamp": "Cop Pulang",
  "Conversation": "Perbualan", "You": "Anda", "MINT Guide": "Panduan MINT",
  "Hi! Ask me about opening hours, tickets, what is on each level, or how to get to MINT.": "Hai! Tanya saya tentang waktu operasi, tiket, pameran di setiap tingkat atau cara ke MINT.",
  "You can write in:": "Anda boleh menulis dalam:", "Thinking...": "Sedang berfikir...", "Quick questions": "Soalan pantas",
  "Tap a question to ask it.": "Ketik soalan untuk bertanya.", "What are your opening hours?": "Apakah waktu operasi anda?",
  "What is on each level?": "Apakah yang terdapat di setiap tingkat?", "How can I contact MINT?": "Bagaimanakah saya boleh menghubungi MINT?",
  "Where can I get help?": "Di manakah saya boleh mendapatkan bantuan?", "Type your question": "Taip soalan anda",
  "Press Enter to send. Press Shift and Enter for a new line.": "Tekan Enter untuk menghantar. Tekan Shift dan Enter untuk baris baharu.",
  "Send": "Hantar", "Sending...": "Sedang menghantar...", "Sorry, I cannot answer right now.": "Maaf, saya tidak dapat menjawab sekarang.",
  "Please check your message and try again.": "Semak mesej anda dan cuba lagi.", "The chatbot is not available at the moment.": "Chatbot tidak tersedia buat masa ini.",
  "Something went wrong on our side.": "Ralat berlaku pada pihak kami.", "We cannot connect. Please check your internet connection.": "Kami tidak dapat menyambung. Semak sambungan internet anda.",
  "This took too long.": "Proses ini mengambil masa terlalu lama.", "The chatbot is not set up yet.": "Chatbot belum disediakan.",
  "The message was cancelled.": "Mesej dibatalkan.", "You can still get help:": "Anda masih boleh mendapatkan bantuan:",
  "Call or WhatsApp": "Telefon atau WhatsApp", "Email": "E-mel", "Go to the Help page": "Pergi ke halaman Bantuan", "Try again": "Cuba lagi",
  "Need help now?": "Perlukan bantuan sekarang?", "Send a message to museum staff. We do not ask for your name.": "Hantar mesej kepada kakitangan muzium. Kami tidak meminta nama anda.",
  "Your message and the area you choose will be shared with museum staff.": "Mesej dan kawasan pilihan anda akan dikongsi dengan kakitangan muzium.",
  "In an emergency, tell a staff member now.": "Dalam kecemasan, maklumkan kakitangan sekarang.", "Call": "Telefon",
  "Where are you?": "Di manakah anda?", "Choose an area": "Pilih kawasan", "Level {level}": "Aras {level}", "I am not sure": "Saya tidak pasti",
  "What help do you need?": "Apakah bantuan yang anda perlukan?", "Send to staff": "Hantar kepada kakitangan",
  "Your message was not sent": "Mesej anda tidak dihantar", "Your message is still in the form.": "Mesej anda masih dalam borang.",
  "Your message was sent to staff": "Mesej anda telah dihantar kepada kakitangan", "Reference number": "Nombor rujukan",
  "What to do next": "Langkah seterusnya", "Safety information": "Maklumat keselamatan", "Stay calm.": "Bertenang.",
  "If you can, move to a safe place.": "Jika boleh, pergi ke tempat yang selamat.", "Tell a museum staff member.": "Maklumkan kakitangan muzium.",
  "Address": "Alamat", "Phone or WhatsApp": "Telefon atau WhatsApp", "Opening hours": "Waktu operasi", "Feedback": "Maklum balas",
  "This is optional. It helps us make the guide better.": "Pilihan. Maklum balas ini membantu kami menambah baik panduan.",
  "How easy was this guide to use?": "Sejauh manakah panduan ini mudah digunakan?", "Very hard": "Sangat sukar", "Hard": "Sukar",
  "Okay": "Sederhana", "Easy": "Mudah", "Very easy": "Sangat mudah", "Send feedback": "Hantar maklum balas",
  "Thank you for your feedback": "Terima kasih atas maklum balas anda", "Your feedback helps us improve the guide.": "Maklum balas anda membantu kami menambah baik panduan.",
  "Send more feedback": "Hantar maklum balas lagi", "Email:": "E-mel:", "Phone:": "Telefon:", "Address:": "Alamat:",
  "Small children’s gift": "Hadiah kecil untuk kanak-kanak", "20% off one museum admission ticket": "Diskaun 20% untuk satu tiket masuk muzium",
  "S$5 FairPrice voucher (demo proposal)": "Baucar FairPrice S$5 (cadangan demo)",
  "Choose a small surprise such as stickers, a pencil, or a mini activity kit.": "Pilih kejutan kecil seperti pelekat, pensel atau kit aktiviti mini.",
  "A proposed demo discount for one museum admission ticket.": "Cadangan diskaun demo untuk satu tiket masuk muzium.",
  "A proposed demo reward only; this is not an issued voucher or an official FairPrice partnership.": "Cadangan ganjaran demo sahaja; ini bukan baucar yang dikeluarkan atau kerjasama rasmi FairPrice.",
  "Out of stock. Please choose another reward.": "Kehabisan stok. Sila pilih ganjaran lain.", "This reward is no longer available.": "Ganjaran ini tidak lagi tersedia.",
  "No rewards yet. Choose one above when you’re ready!": "Belum ada ganjaran. Pilih satu di atas apabila anda bersedia!",
  "Ready to use": "Sedia digunakan", "Used": "Digunakan",
};

const taExtended: VisitorStringDictionary = {
  "stamps": "முத்திரைகள்", "points remaining": "மீதமுள்ள புள்ளிகள்",
  "MINT MUSEUM OF TOYS": "MINT பொம்மை அருங்காட்சியகம்",
  "Find the Moon Rocket XM-12 and scan its code.": "Moon Rocket XM-12-ஐக் கண்டுபிடித்து அதன் குறியீட்டை ஸ்கேன் செய்யுங்கள்.",
  "What is the name of this toy?": "இந்தப் பொம்மையின் பெயர் என்ன?", "Fill in the missing fact.": "விடுபட்ட தகவலை நிரப்பவும்.",
  "The Moon Rocket XM-12 was made in ____.": "Moon Rocket XM-12 ____ நாட்டில் தயாரிக்கப்பட்டது.",
  "Which company made the Moon Rocket XM-12?": "Moon Rocket XM-12-ஐ எந்த நிறுவனம் தயாரித்தது?",
  "Find the Robot Action Dalek and scan its code.": "Robot Action Dalek-ஐக் கண்டுபிடித்து குறியீட்டை ஸ்கேன் செய்யுங்கள்.",
  "The Robot Action Dalek dates to around ____.": "Robot Action Dalek சுமார் ____ ஆண்டைச் சேர்ந்தது.",
  "What color was the museum's battery Dalek?": "அருங்காட்சியகத்தின் மின்கல Dalek என்ன நிறம்?",
  "Find the Lone Star Aqua Jet and scan its code.": "Lone Star Aqua Jet-ஐக் கண்டுபிடித்து குறியீட்டை ஸ்கேன் செய்யுங்கள்.",
  "The Aqua Jet was first released as the ____.": "Aqua Jet முதலில் ____ என்ற பெயரில் வெளியிடப்பட்டது.",
  "Which company made the Lone Star Aqua Jet?": "Lone Star Aqua Jet-ஐ எந்த நிறுவனம் தயாரித்தது?",
  "Find the Demo Comet Rover and scan its code.": "Demo Comet Rover-ஐக் கண்டுபிடித்து குறியீட்டை ஸ்கேன் செய்யுங்கள்.",
  "What is the name of this demo toy?": "இந்த டெமோ பொம்மையின் பெயர் என்ன?", "Fill in the missing demo fact.": "விடுபட்ட டெமோ தகவலை நிரப்பவும்.",
  "The Demo Comet Rover has ____ wheels.": "Demo Comet Rover-இல் ____ சக்கரங்கள் உள்ளன.",
  "How many wheels does the Demo Comet Rover have?": "Demo Comet Rover-இல் எத்தனை சக்கரங்கள் உள்ளன?",
  "Find the Demo Orbit Scout Ship and scan its code.": "Demo Orbit Scout Ship-ஐக் கண்டுபிடித்து குறியீட்டை ஸ்கேன் செய்யுங்கள்.",
  "The Demo Orbit Scout Ship carries ____ astronauts.": "Demo Orbit Scout Ship ____ விண்வெளி வீரர்களை ஏற்றிச் செல்கிறது.",
  "What color are the Demo Orbit Scout Ship's wings?": "Demo Orbit Scout Ship-இன் இறக்கைகள் என்ன நிறம்?",
  "Restore the launch dial.": "ஏவல் டயலைச் சரிசெய்யுங்கள்.",
  "The Toy Time Machine is silent. Solve five toy clues to bring back its power.": "பொம்மை கால இயந்திரம் அமைதியாக உள்ளது. அதன் சக்தியை மீட்டெடுக்க ஐந்து பொம்மைக் குறிப்புகளைத் தீர்க்கவும்.",
  "The launch dial glows again. The machine can start!": "ஏவல் டயல் மீண்டும் ஒளிர்கிறது. இயந்திரத்தைத் தொடங்கலாம்!",
  "Restore the direction dial.": "திசை டயலைச் சரிசெய்யுங்கள்.",
  "The machine has power, but it needs a direction. Solve five more toy clues.": "இயந்திரத்திற்கு சக்தி உள்ளது, ஆனால் திசை தேவை. மேலும் ஐந்து பொம்மைக் குறிப்புகளைத் தீர்க்கவும்.",
  "The direction dial is set. One more dial to go!": "திசை டயல் அமைக்கப்பட்டது. இன்னும் ஒரு டயல் மட்டுமே!",
  "Restore the home dial.": "வீடு திரும்பும் டயலைச் சரிசெய்யுங்கள்.",
  "The final dial will let the toys return home. Solve the last five toy clues.": "இறுதி டயல் பொம்மைகள் வீடு திரும்ப உதவும். கடைசி ஐந்து குறிப்புகளைத் தீர்க்கவும்.",
  "All three dials are restored. The Toy Time Machine is ready!": "மூன்று டயல்களும் சரிசெய்யப்பட்டன. பொம்மை கால இயந்திரம் தயார்!",
  "Launch Stamp": "ஏவல் முத்திரை", "Direction Stamp": "திசை முத்திரை", "Home Stamp": "வீடு திரும்பும் முத்திரை",
  "Conversation": "உரையாடல்", "You": "நீங்கள்", "MINT Guide": "MINT வழிகாட்டி",
  "Hi! Ask me about opening hours, tickets, what is on each level, or how to get to MINT.": "வணக்கம்! திறந்திருக்கும் நேரம், நுழைவுச்சீட்டுகள், ஒவ்வொரு தளத்திலும் உள்ளவை அல்லது MINT-க்கு வரும் வழி பற்றி கேளுங்கள்.",
  "You can write in:": "இந்த மொழிகளில் எழுதலாம்:", "Thinking...": "சிந்திக்கிறது...", "Quick questions": "விரைவு கேள்விகள்",
  "Tap a question to ask it.": "கேள்வியைக் கேட்க அதைத் தட்டவும்.", "What are your opening hours?": "உங்கள் திறந்திருக்கும் நேரம் என்ன?",
  "What is on each level?": "ஒவ்வொரு தளத்திலும் என்ன உள்ளது?", "How can I contact MINT?": "MINT-ஐ எவ்வாறு தொடர்புகொள்வது?",
  "Where can I get help?": "எங்கே உதவி பெறலாம்?", "Type your question": "உங்கள் கேள்வியைத் தட்டச்சு செய்யுங்கள்",
  "Press Enter to send. Press Shift and Enter for a new line.": "அனுப்ப Enter அழுத்தவும். புதிய வரிக்கு Shift மற்றும் Enter அழுத்தவும்.",
  "Send": "அனுப்பு", "Sending...": "அனுப்பப்படுகிறது...", "Sorry, I cannot answer right now.": "மன்னிக்கவும், இப்போது பதிலளிக்க முடியவில்லை.",
  "Please check your message and try again.": "செய்தியைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.", "The chatbot is not available at the moment.": "உரையாடல் உதவியாளர் தற்போது கிடைக்கவில்லை.",
  "Something went wrong on our side.": "எங்கள் பக்கத்தில் பிழை ஏற்பட்டது.", "We cannot connect. Please check your internet connection.": "இணைக்க முடியவில்லை. இணைய இணைப்பைச் சரிபார்க்கவும்.",
  "This took too long.": "இது அதிக நேரம் எடுத்தது.", "The chatbot is not set up yet.": "உரையாடல் உதவியாளர் இன்னும் அமைக்கப்படவில்லை.",
  "The message was cancelled.": "செய்தி ரத்து செய்யப்பட்டது.", "You can still get help:": "இன்னும் உதவி பெறலாம்:",
  "Call or WhatsApp": "அழைப்பு அல்லது WhatsApp", "Email": "மின்னஞ்சல்", "Go to the Help page": "உதவிப் பக்கத்திற்குச் செல்லவும்", "Try again": "மீண்டும் முயற்சிக்கவும்",
  "Need help now?": "இப்போது உதவி வேண்டுமா?", "Send a message to museum staff. We do not ask for your name.": "அருங்காட்சியகப் பணியாளர்களுக்கு செய்தி அனுப்புங்கள். உங்கள் பெயரைக் கேட்கமாட்டோம்.",
  "Your message and the area you choose will be shared with museum staff.": "உங்கள் செய்தியும் நீங்கள் தேர்ந்தெடுக்கும் பகுதியும் அருங்காட்சியகப் பணியாளர்களுடன் பகிரப்படும்.",
  "In an emergency, tell a staff member now.": "அவசரநிலையில் உடனே பணியாளரிடம் தெரிவிக்கவும்.", "Call": "அழைக்கவும்",
  "Where are you?": "நீங்கள் எங்கே இருக்கிறீர்கள்?", "Choose an area": "பகுதியைத் தேர்ந்தெடுக்கவும்", "Level {level}": "தளம் {level}", "I am not sure": "எனக்குத் தெரியவில்லை",
  "What help do you need?": "என்ன உதவி தேவை?", "Send to staff": "பணியாளருக்கு அனுப்பு", "Your message was not sent": "உங்கள் செய்தி அனுப்பப்படவில்லை",
  "Your message is still in the form.": "உங்கள் செய்தி படிவத்தில் உள்ளது.", "Your message was sent to staff": "உங்கள் செய்தி பணியாளருக்கு அனுப்பப்பட்டது",
  "Reference number": "குறிப்பு எண்", "What to do next": "அடுத்து என்ன செய்ய வேண்டும்", "Safety information": "பாதுகாப்புத் தகவல்",
  "Stay calm.": "அமைதியாக இருங்கள்.", "If you can, move to a safe place.": "முடிந்தால் பாதுகாப்பான இடத்திற்குச் செல்லுங்கள்.",
  "Tell a museum staff member.": "அருங்காட்சியகப் பணியாளரிடம் தெரிவிக்கவும்.", "Address": "முகவரி",
  "Phone or WhatsApp": "தொலைபேசி அல்லது WhatsApp", "Opening hours": "திறந்திருக்கும் நேரம்", "Feedback": "கருத்து",
  "This is optional. It helps us make the guide better.": "இது விருப்பமானது. வழிகாட்டியை மேம்படுத்த உதவும்.",
  "How easy was this guide to use?": "இந்த வழிகாட்டியைப் பயன்படுத்துவது எவ்வளவு எளிதாக இருந்தது?",
  "Very hard": "மிகக் கடினம்", "Hard": "கடினம்", "Okay": "பரவாயில்லை", "Easy": "எளிது", "Very easy": "மிக எளிது",
  "Send feedback": "கருத்தை அனுப்பு", "Thank you for your feedback": "உங்கள் கருத்துக்கு நன்றி",
  "Your feedback helps us improve the guide.": "வழிகாட்டியை மேம்படுத்த உங்கள் கருத்து உதவுகிறது.", "Send more feedback": "மேலும் கருத்து அனுப்பு",
  "Profile: {name}": "சுயவிவரம்: {name}", "How should we address you?": "உங்களை எவ்வாறு அழைக்க வேண்டும்?",
  "What would you like to know?": "நீங்கள் என்ன அறிய விரும்புகிறீர்கள்?",
  "Tell us how we can help...": "நாங்கள் எவ்வாறு உதவலாம் என்பதைச் சொல்லுங்கள்...", "A little wonder, right on Seah Street.": "Seah Street-இல் ஒரு சிறிய அதிசயம்.",
  "Find us in the heart of Singapore. Plan your visit or get in touch below.": "சிங்கப்பூரின் மையத்தில் எங்களைக் காணலாம். உங்கள் வருகையைத் திட்டமிடுங்கள் அல்லது கீழே தொடர்புகொள்ளுங்கள்.",
  "Email:": "மின்னஞ்சல்:", "Phone:": "தொலைபேசி:", "Address:": "முகவரி:",
};

const zhMissionExtras: VisitorStringDictionary = {
  "Yellow": "黄色", "Blue": "蓝色", "Green": "绿色", "Red": "红色", "Four": "四", "Six": "六", "Eight": "八",
  "Yonezawa Toys": "Yonezawa Toys", "Louis Marx and Company": "Louis Marx and Company", "Lone Star Products": "Lone Star Products",
  "United Kingdom": "英国", "Japan": "日本", "Outerspace": "外太空",
  "Moon Rocket XM-12": "月球火箭 XM-12", "Demo Comet Rover": "演示彗星漫游车", "Demo Orbit Scout Ship": "演示轨道侦察飞船",
  "Made by Yonezawa Toys in Japan. The rocket has two pilots under a clear canopy and a nose wheel in its cockpit.": "由日本 Yonezawa Toys 制造。火箭有透明座舱罩下的两名飞行员，驾驶舱内设有前轮。",
  "Made by Louis Marx and Company in the United Kingdom. The museum describes a yellow battery toy dating to around 1974.": "由英国 Louis Marx and Company 制造。博物馆介绍这款黄色电池玩具约为 1974 年的产品。",
  "Made by Lone Star Products in the United Kingdom. It was first released as the Dan Dare Aqua Jet.": "由英国 Lone Star Products 制造，最初以 Dan Dare Aqua Jet 名称发行。",
  "Demo exhibit. A six-wheel blue rover built by the MINT Demo Workshop. It carries a yellow sample container.": "演示展品。由 MINT 演示工坊制作的蓝色六轮漫游车，载有黄色样品容器。",
  "Demo exhibit. A silver toy spacecraft built by the MINT Demo Workshop. Two astronauts sit in its cockpit beneath red wings.": "演示展品。由 MINT 演示工坊制作的银色玩具飞船。两名宇航员坐在红色机翼下的驾驶舱内。",
};
const msMissionExtras: VisitorStringDictionary = {
  "Yellow": "Kuning", "Blue": "Biru", "Green": "Hijau", "Red": "Merah", "Four": "Empat", "Six": "Enam", "Eight": "Lapan",
  "United Kingdom": "United Kingdom", "Japan": "Jepun", "Outerspace": "Angkasa Lepas",
  "Made by Yonezawa Toys in Japan. The rocket has two pilots under a clear canopy and a nose wheel in its cockpit.": "Dibuat oleh Yonezawa Toys di Jepun. Roket ini mempunyai dua juruterbang di bawah kanopi lutsinar dan roda hadapan di kokpit.",
  "Made by Louis Marx and Company in the United Kingdom. The museum describes a yellow battery toy dating to around 1974.": "Dibuat oleh Louis Marx and Company di United Kingdom. Muzium menyatakan mainan bateri kuning ini berasal sekitar tahun 1974.",
  "Made by Lone Star Products in the United Kingdom. It was first released as the Dan Dare Aqua Jet.": "Dibuat oleh Lone Star Products di United Kingdom. Ia mula-mula dikeluarkan sebagai Dan Dare Aqua Jet.",
  "Demo exhibit. A six-wheel blue rover built by the MINT Demo Workshop. It carries a yellow sample container.": "Pameran demo. Rover biru enam roda buatan Bengkel Demo MINT ini membawa bekas sampel kuning.",
  "Demo exhibit. A silver toy spacecraft built by the MINT Demo Workshop. Two astronauts sit in its cockpit beneath red wings.": "Pameran demo. Kapal angkasa mainan perak buatan Bengkel Demo MINT ini mempunyai dua angkasawan di kokpit di bawah sayap merah.",
};
const taMissionExtras: VisitorStringDictionary = {
  "Yellow": "மஞ்சள்", "Blue": "நீலம்", "Green": "பச்சை", "Red": "சிவப்பு", "Four": "நான்கு", "Six": "ஆறு", "Eight": "எட்டு",
  "United Kingdom": "ஐக்கிய இராச்சியம்", "Japan": "ஜப்பான்", "Outerspace": "விண்வெளி",
  "Made by Yonezawa Toys in Japan. The rocket has two pilots under a clear canopy and a nose wheel in its cockpit.": "ஜப்பானின் Yonezawa Toys நிறுவனம் தயாரித்தது. தெளிவான மூடியின் கீழ் இரண்டு விமானிகளும் காக்பிட்டில் முன்சக்கரமும் உள்ளன.",
  "Made by Louis Marx and Company in the United Kingdom. The museum describes a yellow battery toy dating to around 1974.": "ஐக்கிய இராச்சியத்தின் Louis Marx and Company தயாரித்தது. மஞ்சள் மின்கலப் பொம்மை சுமார் 1974-ஆம் ஆண்டைச் சேர்ந்தது என அருங்காட்சியகம் கூறுகிறது.",
  "Made by Lone Star Products in the United Kingdom. It was first released as the Dan Dare Aqua Jet.": "ஐக்கிய இராச்சியத்தின் Lone Star Products தயாரித்தது. இது முதலில் Dan Dare Aqua Jet என்ற பெயரில் வெளியிடப்பட்டது.",
  "Demo exhibit. A six-wheel blue rover built by the MINT Demo Workshop. It carries a yellow sample container.": "டெமோ காட்சிப்பொருள். MINT டெமோ பணிமனை உருவாக்கிய ஆறு சக்கர நீல ரோவர் மஞ்சள் மாதிரிக் கொள்கலனை ஏந்துகிறது.",
  "Demo exhibit. A silver toy spacecraft built by the MINT Demo Workshop. Two astronauts sit in its cockpit beneath red wings.": "டெமோ காட்சிப்பொருள். MINT டெமோ பணிமனை உருவாக்கிய வெள்ளி பொம்மை விண்கலத்தின் சிவப்பு இறக்கைகளின் கீழ் காக்பிட்டில் இரண்டு விண்வெளி வீரர்கள் உள்ளனர்.",
};
const zhHelpExtras: VisitorStringDictionary = {
  "characters left": "个字符剩余", "characters too many": "个字符超出",
  "Page buttons and labels in Chinese, Malay and Tamil (needs the language setting)": "中文、马来语和泰米尔语的页面按钮及标签（需设置语言）",
  "Hand over to a staff member (human in the loop)": "转交工作人员处理（人工协助）",
  "Your message and the area you choose will be shared with museum staff.": "你的消息和所选区域将与博物馆工作人员共享。",
  "Choose the level you are on. If you do not know, choose \"I am not sure\".": "选择你所在的楼层。如果不确定，请选择“我不确定”。",
  "More about where you are (optional)": "关于你所在位置的更多信息（可选）", "For example: near the lift.": "例如：电梯附近。",
  "Write a short message. Up to 500 characters.": "请简短描述，最多 500 个字符。",
  "Please choose an area. You can choose \"I am not sure\".": "请选择一个区域。你可以选择“我不确定”。",
  "Please keep this to {max} characters or fewer.": "请将内容控制在 {max} 个字符以内。",
  "Please tell us what help you need.": "请告诉我们你需要什么帮助。",
  "Your message was not sent": "消息未能发送", "Your message is still in the form.": "消息仍保留在表单中。",
  "You can also call or WhatsApp": "你也可以致电或使用 WhatsApp", "Your message was sent to staff": "消息已发送给工作人员",
  "Reference number": "参考编号", "What to do next": "接下来该怎么做",
  "If it is safe, stay near the area you chose.": "如果安全，请留在你选择的区域附近。",
  "If you need help faster, speak to any staff member.": "如需尽快获得帮助，请联系任意工作人员。",
  "Tell staff your reference number if they ask.": "如工作人员询问，请提供你的参考编号。", "Send another message": "再发送一条消息",
  "Safety information": "安全信息", "If something is wrong:": "如果发生问题：", "In an emergency, call": "紧急情况下请拨打",
  "for ambulance or fire": "呼叫救护车或消防", "or": "或", "for police": "报警",
  "What could we do better? (optional)": "我们可以如何改进？（选填）",
  "Please do not write your name or contact details. Up to 500 characters.": "请勿填写姓名或联系方式。最多 500 个字符。",
  "Please choose how easy the guide was to use.": "请选择这份指南的使用难度。",
  "Your comment is too long. Please use 500 characters or fewer.": "意见过长。请控制在 500 个字符以内。",
  "Your feedback was not sent": "反馈未能发送", "Thank you for your feedback": "感谢你的反馈",
  "Your feedback helps us improve the guide.": "你的反馈有助于我们改进指南。", "Send more feedback": "再发送反馈",
  "Refresh the knowledge base before the final demo (n8n/knowledge)": "最终演示前更新知识库（n8n/knowledge）",
};
const msHelpExtras: VisitorStringDictionary = {
  "characters left": " aksara lagi", "characters too many": " aksara berlebihan",
  "Page buttons and labels in Chinese, Malay and Tamil (needs the language setting)": "Butang dan label halaman dalam bahasa Cina, Melayu dan Tamil (memerlukan tetapan bahasa)",
  "Hand over to a staff member (human in the loop)": "Serahkan kepada kakitangan untuk bantuan manusia",
  "Choose the level you are on. If you do not know, choose \"I am not sure\".": "Pilih aras anda. Jika tidak pasti, pilih \"Saya tidak pasti\".",
  "More about where you are (optional)": "Maklumat lanjut tentang lokasi anda (pilihan)", "For example: near the lift.": "Contohnya: berhampiran lif.",
  "Write a short message. Up to 500 characters.": "Tulis mesej ringkas. Sehingga 500 aksara.",
  "Please choose an area. You can choose \"I am not sure\".": "Pilih kawasan. Anda boleh memilih \"Saya tidak pasti\".",
  "Please keep this to {max} characters or fewer.": "Hadkan kepada {max} aksara atau kurang.",
  "Please tell us what help you need.": "Beritahu kami bantuan yang anda perlukan.",
  "Your message and the area you choose will be shared with museum staff.": "Mesej dan kawasan pilihan anda akan dikongsi dengan kakitangan muzium.",
  "Your message was not sent": "Mesej anda tidak dihantar", "Your message is still in the form.": "Mesej anda masih dalam borang.",
  "You can also call or WhatsApp": "Anda juga boleh menelefon atau menggunakan WhatsApp",
  "Your message was sent to staff": "Mesej anda telah dihantar kepada kakitangan", "Reference number": "Nombor rujukan",
  "What to do next": "Langkah seterusnya", "If it is safe, stay near the area you chose.": "Jika selamat, kekal berhampiran kawasan yang anda pilih.",
  "If you need help faster, speak to any staff member.": "Jika memerlukan bantuan segera, bercakap dengan mana-mana kakitangan.",
  "Tell staff your reference number if they ask.": "Berikan nombor rujukan anda jika diminta oleh kakitangan.", "Send another message": "Hantar mesej lain",
  "If something is wrong:": "Jika berlaku masalah:", "In an emergency, call": "Dalam kecemasan, telefon",
  "for ambulance or fire": "untuk ambulans atau bomba", "or": "atau", "for police": "untuk polis",
  "What could we do better? (optional)": "Apakah yang boleh kami perbaik? (pilihan)",
  "Please do not write your name or contact details. Up to 500 characters.": "Jangan tulis nama atau butiran hubungan anda. Sehingga 500 aksara.",
  "Please choose how easy the guide was to use.": "Pilih tahap kemudahan menggunakan panduan ini.",
  "Your comment is too long. Please use 500 characters or fewer.": "Komen anda terlalu panjang. Gunakan 500 aksara atau kurang.",
  "Your feedback was not sent": "Maklum balas anda tidak dihantar",
  "Refresh the knowledge base before the final demo (n8n/knowledge)": "Kemas kini pangkalan pengetahuan sebelum demo akhir (n8n/knowledge)",
};
const taHelpExtras: VisitorStringDictionary = {
  "characters left": " எழுத்துகள் மீதம்", "characters too many": " எழுத்துகள் அதிகம்",
  "Page buttons and labels in Chinese, Malay and Tamil (needs the language setting)": "சீனம், மலாய், தமிழ் மொழிகளில் பக்கப் பொத்தான்கள் மற்றும் குறிச்சொற்கள் (மொழி அமைப்பு தேவை)",
  "Hand over to a staff member (human in the loop)": "பணியாளரிடம் ஒப்படைத்து மனித உதவி பெறுதல்",
  "Choose the level you are on. If you do not know, choose \"I am not sure\".": "நீங்கள் இருக்கும் தளத்தைத் தேர்ந்தெடுக்கவும். தெரியாவிட்டால் \"எனக்குத் தெரியவில்லை\" என்பதைத் தேர்ந்தெடுக்கவும்.",
  "More about where you are (optional)": "நீங்கள் இருக்கும் இடம் பற்றிய கூடுதல் விவரம் (விருப்பம்)", "For example: near the lift.": "உதாரணம்: மின்தூக்கி அருகில்.",
  "Write a short message. Up to 500 characters.": "சுருக்கமான செய்தியை எழுதுங்கள். அதிகபட்சம் 500 எழுத்துகள்.",
  "Please choose an area. You can choose \"I am not sure\".": "ஒரு பகுதியைத் தேர்ந்தெடுக்கவும். \"எனக்குத் தெரியவில்லை\" என்பதைத் தேர்ந்தெடுக்கலாம்.",
  "Please keep this to {max} characters or fewer.": "{max} எழுத்துகள் அல்லது அதற்குள் வைத்திருக்கவும்.",
  "Please tell us what help you need.": "உங்களுக்கு என்ன உதவி தேவை என்பதைச் சொல்லுங்கள்.",
  "Your message and the area you choose will be shared with museum staff.": "உங்கள் செய்தியும் நீங்கள் தேர்ந்தெடுக்கும் பகுதியும் அருங்காட்சியகப் பணியாளர்களுடன் பகிரப்படும்.",
  "Your message was not sent": "உங்கள் செய்தி அனுப்பப்படவில்லை", "Your message is still in the form.": "உங்கள் செய்தி படிவத்தில் உள்ளது.",
  "You can also call or WhatsApp": "அழைக்கலாம் அல்லது WhatsApp பயன்படுத்தலாம்",
  "Your message was sent to staff": "உங்கள் செய்தி பணியாளருக்கு அனுப்பப்பட்டது", "Reference number": "குறிப்பு எண்",
  "What to do next": "அடுத்து என்ன செய்ய வேண்டும்", "If it is safe, stay near the area you chose.": "பாதுகாப்பாக இருந்தால், நீங்கள் தேர்ந்தெடுத்த பகுதியின் அருகில் இருங்கள்.",
  "If you need help faster, speak to any staff member.": "விரைவாக உதவி தேவைப்பட்டால் பணியாளரிடம் பேசுங்கள்.",
  "Tell staff your reference number if they ask.": "கேட்டால் பணியாளரிடம் குறிப்பு எண்ணைச் சொல்லுங்கள்.", "Send another message": "மற்றொரு செய்தியை அனுப்பவும்",
  "If something is wrong:": "ஏதேனும் பிரச்சினை ஏற்பட்டால்:", "In an emergency, call": "அவசரநிலையில் அழைக்கவும்",
  "for ambulance or fire": "ஆம்புலன்ஸ் அல்லது தீயணைப்புக்கு", "or": "அல்லது", "for police": "காவல்துறைக்கு",
  "What could we do better? (optional)": "நாங்கள் எதை மேம்படுத்தலாம்? (விருப்பம்)",
  "Please do not write your name or contact details. Up to 500 characters.": "பெயர் அல்லது தொடர்பு விவரங்களை எழுத வேண்டாம். அதிகபட்சம் 500 எழுத்துகள்.",
  "Please choose how easy the guide was to use.": "வழிகாட்டியைப் பயன்படுத்துவது எவ்வளவு எளிதாக இருந்தது என்பதைத் தேர்ந்தெடுக்கவும்.",
  "Your comment is too long. Please use 500 characters or fewer.": "கருத்து மிக நீளமாக உள்ளது. 500 எழுத்துகள் அல்லது அதற்குள் பயன்படுத்தவும்.",
  "Your feedback was not sent": "உங்கள் கருத்து அனுப்பப்படவில்லை",
};

const msAppExtras: VisitorStringDictionary = {
  "Adventure complete! You earned {points} points. Choose your reward.": "Pengembaraan selesai! Anda memperoleh {points} mata. Pilih ganjaran anda.",
  "Adventure complete! Your one-time {points}-point game bonus is saved. Choose your reward.": "Pengembaraan selesai! Bonus permainan sekali sahaja sebanyak {points} mata telah disimpan. Pilih ganjaran anda.",
  "You already earned the one-time {points}-point game bonus. Restarting the game does not earn more points.": "Anda telah memperoleh bonus permainan sekali sahaja sebanyak {points} mata. Memulakan semula permainan tidak memberikan mata tambahan.",
  "Complete all three missions to earn {points} points.": "Selesaikan ketiga-tiga misi untuk memperoleh {points} mata.",
  "This prototype uses sample QR codes and browser saved progress. Museum photos, physical placements, label wording, and real reward rules still need approval.": "Prototaip ini menggunakan kod QR contoh dan kemajuan yang disimpan dalam pelayar. Foto muzium, lokasi fizikal, teks label dan peraturan ganjaran sebenar masih memerlukan kelulusan.",
  "That code belongs to another toy. Keep looking.": "Kod itu milik mainan lain. Teruskan mencari.",
  "Not quite. Check the toy information and try again.": "Belum tepat. Semak maklumat mainan dan cuba lagi.",
  "We could not save your game progress in this browser. Check browser storage and try again.": "Kemajuan permainan tidak dapat disimpan dalam pelayar ini. Semak storan pelayar dan cuba lagi.",
  "This question needs a written answer. Scanning cannot skip it.": "Soalan ini memerlukan jawapan bertulis. Imbasan tidak boleh melangkauinya.",
  "Correct! Next clue unlocked.": "Betul! Petunjuk seterusnya dibuka.", "Stamp collected! ": "Cop dikumpulkan! ",
  "We could not save the restarted game in this browser. Check browser storage and try again.": "Permainan yang dimulakan semula tidak dapat disimpan. Semak storan pelayar dan cuba lagi.",
  "Demo restarted. Your points and reward history stay saved, and this game bonus can only be earned once.": "Demo dimulakan semula. Mata dan sejarah ganjaran kekal disimpan; bonus permainan hanya boleh diperoleh sekali.",
  "The Toy Time Machine offers a one-time total of 20 points after all three missions are complete. Replaying the game will not earn more points. Reward costs and stock are demo settings; real rewards require secure server validation.": "Mesin Masa Mainan memberikan sejumlah 20 mata sekali sahaja selepas ketiga-tiga misi selesai. Bermain semula tidak memberikan mata tambahan. Kos dan stok ganjaran ialah tetapan demo; ganjaran sebenar memerlukan pengesahan pelayan yang selamat.",
  "Browser storage is unavailable. Progress and rewards may not save; redemptions are disabled until storage is available.": "Storan pelayar tidak tersedia. Kemajuan dan ganjaran mungkin tidak disimpan; penebusan dilumpuhkan sehingga storan tersedia.",
  "{stock} available (demo stock)": "{stock} tersedia (stok demo)", "Demo only · no voucher code issued": "Demo sahaja · tiada kod baucar dikeluarkan",
  "You need {points} more points": "Anda memerlukan {points} mata lagi", "You need {points} more points.": "Anda memerlukan {points} mata lagi.",
  "Demo-only reference: {id}": "Rujukan demo sahaja: {id}", "Reward reserved! Your demo-only reference is {id}.": "Ganjaran ditempah! Nombor rujukan demo anda ialah {id}.",
  "We could not save this redemption on this browser. No points were deducted; please check your browser storage and try again.": "Penebusan tidak dapat disimpan dalam pelayar ini. Tiada mata ditolak; semak storan pelayar dan cuba lagi.",
  "This is a demo proposal, not a real voucher or an official FairPrice partnership. No voucher code will be created.": "Ini cadangan demo, bukan baucar sebenar atau kerjasama rasmi FairPrice. Tiada kod baucar akan dibuat.",
  "This game offers a one-time total of {points} points. Replaying will not earn more.": "Permainan ini menawarkan sejumlah {points} mata sekali sahaja. Bermain semula tidak memberikan mata tambahan.",
  "Planned for this page": "Perancangan halaman ini",
};
const taAppExtras: VisitorStringDictionary = {
  "Adventure complete! You earned {points} points. Choose your reward.": "சாகசம் நிறைவு! {points} புள்ளிகள் பெற்றுள்ளீர்கள். உங்கள் வெகுமதியைத் தேர்ந்தெடுக்கவும்.",
  "Adventure complete! Your one-time {points}-point game bonus is saved. Choose your reward.": "சாகசம் நிறைவு! ஒருமுறை கிடைக்கும் {points} புள்ளி விளையாட்டு போனஸ் சேமிக்கப்பட்டது. வெகுமதியைத் தேர்ந்தெடுக்கவும்.",
  "You already earned the one-time {points}-point game bonus. Restarting the game does not earn more points.": "ஒருமுறை கிடைக்கும் {points} புள்ளி போனஸை ஏற்கெனவே பெற்றுள்ளீர்கள். விளையாட்டை மறுதொடக்கம் செய்தால் கூடுதல் புள்ளிகள் கிடைக்காது.",
  "Complete all three missions to earn {points} points.": "{points} புள்ளிகள் பெற மூன்று பணிகளையும் நிறைவு செய்யுங்கள்.",
  "This game offers a one-time total of {points} points. Replaying will not earn more.": "இந்த விளையாட்டில் ஒருமுறை மட்டும் மொத்தம் {points} புள்ளிகள் கிடைக்கும். மீண்டும் விளையாடினால் கூடுதல் புள்ளிகள் கிடைக்காது.",
  "This prototype uses sample QR codes and browser saved progress. Museum photos, physical placements, label wording, and real reward rules still need approval.": "இந்த முன்மாதிரி மாதிரி QR குறியீடுகளையும் உலாவியில் சேமிக்கப்பட்ட முன்னேற்றத்தையும் பயன்படுத்துகிறது. அருங்காட்சியகப் படங்கள், உண்மையான இடங்கள், குறிப்பு உரைகள் மற்றும் வெகுமதி விதிகளுக்கு இன்னும் ஒப்புதல் தேவை.",
  "That code belongs to another toy. Keep looking.": "அந்தக் குறியீடு வேறொரு பொம்மைக்குரியது. தொடர்ந்து தேடுங்கள்.",
  "Not quite. Check the toy information and try again.": "சரியில்லை. பொம்மைத் தகவலைப் பார்த்து மீண்டும் முயற்சிக்கவும்.",
  "We could not save your game progress in this browser. Check browser storage and try again.": "இந்த உலாவியில் விளையாட்டு முன்னேற்றத்தைச் சேமிக்க முடியவில்லை. உலாவி சேமிப்பகத்தைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
  "This question needs a written answer. Scanning cannot skip it.": "இந்தக் கேள்விக்கு எழுதப்பட்ட பதில் தேவை. ஸ்கேன் செய்வதால் இதைத் தவிர்க்க முடியாது.",
  "Correct! Next clue unlocked.": "சரி! அடுத்த குறிப்பு திறக்கப்பட்டது.", "Stamp collected! ": "முத்திரை சேகரிக்கப்பட்டது! ",
  "We could not save the restarted game in this browser. Check browser storage and try again.": "மறுதொடக்கம் செய்த விளையாட்டைச் சேமிக்க முடியவில்லை. உலாவி சேமிப்பகத்தைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
  "Demo restarted. Your points and reward history stay saved, and this game bonus can only be earned once.": "டெமோ மறுதொடக்கம் செய்யப்பட்டது. புள்ளிகளும் வெகுமதி வரலாறும் சேமிக்கப்படும்; இந்த விளையாட்டு போனஸை ஒருமுறை மட்டுமே பெறலாம்.",
  "The Toy Time Machine offers a one-time total of 20 points after all three missions are complete. Replaying the game will not earn more points. Reward costs and stock are demo settings; real rewards require secure server validation.": "மூன்று பணிகளையும் முடித்த பிறகு பொம்மை கால இயந்திரம் ஒருமுறை மொத்தம் 20 புள்ளிகளை வழங்கும். மீண்டும் விளையாடினால் கூடுதல் புள்ளிகள் கிடைக்காது. வெகுமதி செலவும் இருப்பும் டெமோ அமைப்புகள்; உண்மையான வெகுமதிகளுக்கு பாதுகாப்பான சர்வர் சரிபார்ப்பு தேவை.",
  "Browser storage is unavailable. Progress and rewards may not save; redemptions are disabled until storage is available.": "உலாவி சேமிப்பகம் கிடைக்கவில்லை. முன்னேற்றமும் வெகுமதிகளும் சேமிக்கப்படாமல் இருக்கலாம்; சேமிப்பகம் கிடைக்கும் வரை பெறுதல் முடக்கப்பட்டுள்ளது.",
  "{stock} available (demo stock)": "{stock} கிடைக்கும் (டெமோ இருப்பு)", "Demo only · no voucher code issued": "டெமோ மட்டும் · வவுச்சர் குறியீடு வழங்கப்படாது",
  "You need {points} more points": "மேலும் {points} புள்ளிகள் தேவை", "You need {points} more points.": "மேலும் {points} புள்ளிகள் தேவை.",
  "Demo-only reference: {id}": "டெமோ குறிப்பு மட்டும்: {id}", "Reward reserved! Your demo-only reference is {id}.": "வெகுமதி ஒதுக்கப்பட்டது! டெமோ குறிப்பு எண்: {id}.",
  "We could not save this redemption on this browser. No points were deducted; please check your browser storage and try again.": "இந்த உலாவியில் பெறுதலைச் சேமிக்க முடியவில்லை. புள்ளிகள் கழிக்கப்படவில்லை; சேமிப்பகத்தைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
  "This is a demo proposal, not a real voucher or an official FairPrice partnership. No voucher code will be created.": "இது டெமோ முன்மொழிவு; உண்மையான வவுச்சரோ FairPrice அதிகாரப்பூர்வ கூட்டாண்மையோ அல்ல. வவுச்சர் குறியீடு உருவாக்கப்படாது.",
  "Planned for this page": "இந்தப் பக்கத்திற்கான திட்டம்",
};

const dictionaries: Record<ChatLanguage, VisitorStrings> = {
  en,
  zh: { ...zh, ...zhExtended, ...zhMissionExtras, ...zhHelpExtras },
  ms: { ...ms, ...msExtended, ...msMissionExtras, ...msHelpExtras, ...msAppExtras },
  ta: { ...ta, ...taExtended, ...taMissionExtras, ...taHelpExtras, ...taAppExtras },
};

export function getVisitorStrings(language: ChatLanguage): VisitorStrings {
  return dictionaries[language] ?? en;
}

export function translateVisitorText(text: string, language: ChatLanguage): string {
  const strings = getVisitorStrings(language);
  const translated = strings[text];
  if (translated !== undefined) return translated;
  const characterCount = /^(-?\d+) characters (left|too many)$/.exec(text);
  if (characterCount) {
    const suffix = characterCount[2] === "left" ? " characters left" : " characters too many";
    const localizedSuffix = strings[suffix.trim()] ?? suffix;
    return `${characterCount[1]}${localizedSuffix}`;
  }
  return text;
}

export function localizeVisitorTree<T>(value: T, language: ChatLanguage): T {
  if (typeof value === "string") return translateVisitorText(value, language) as T;
  if (typeof value === "function") {
    return ((...args: unknown[]) =>
      translateVisitorText(String((value as (...values: unknown[]) => unknown)(...args)), language)) as T;
  }
  if (Array.isArray(value))
    return value.map((entry) => localizeVisitorTree(entry, language)) as T;
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [key, localizeVisitorTree(entry, language)]),
    ) as T;
  }
  return value;
}
